services:
  usersapi:
    image: ${DOCKER_REGISTRY-}usersapi
    ports: 
     - "8080:80"
    build:
      context: .
      dockerfile: UsersApi/Dockerfile
    environment:
      LocalStack__Config__LocalStackHost: 'localstack'
    depends_on:
      - localstack

  localstack:
    container_name: ${DOCKER_REGISTRY-}usersapi-localstack
    image: localstack/localstack
    ports:
      - "4510-4559:4510-4559"  # external service port range
      - "4566:4566"            # LocalStack Edge Proxy
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=sqs,s3  
      - EXTRA_CORS_ALLOWED_ORIGINS=https://app.localstack.cloud.
    volumes:
      - "./localstack-volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"